Minor check for http repos that are anonymous
Cloud-Foundations/golib pull request #73
Opened 2022-10-18 20:56 UTC by cviecco

2022-10-18 22:29 UTC, rgooch requested changes
The tests will break in isolated environments, which could break automated build/test sytems. Can you add a probe to check if access is available, and not throw errors if there is no access?

2022-10-18 22:29 UTC, rgooch commented on pkg/git/repowatch/getKey.go
> +
Please remove blank line.

2022-10-18 22:29 UTC, rgooch commented on pkg/git/repowatch/getKey.go
> +
Please add documentation (perhaps move from `getAuthSSH`), since this is the entry point.

2022-10-18 22:29 UTC, rgooch commented on pkg/git/repowatch/impl.go
> +
Please delete blank line.

2022-10-18 22:29 UTC, rgooch commented on pkg/git/repowatch/impl.go
> +
Please delete blank line.

2022-10-18 22:29 UTC, rgooch commented on pkg/git/repowatch/impl_test.go
> +	_, _, err = setupGitRepository(ctx, config, params, metrics) //(*git.Worktree, string, error) {
Please delete commented code.

2022-10-18 22:29 UTC, rgooch commented on pkg/git/repowatch/impl_test.go
> +	ctx := context.Background()
Please use `context.TODO()`.

2022-10-19 17:52 UTC, rgooch commented on pkg/git/repowatch/getKey.go
> +// getAuthSSH will return with a null authentication on http repositories, and
s/getAuthSSH/getAuth/

2022-10-19 19:06 UTC, cviecco commented on pkg/git/repowatch/getKey.go
> +// getAuthSSH will return with a null authentication on http repositories, and
done

2022-10-19 19:35 UTC, rgooch approved these changes

2022-10-19 21:00 UTC, merged